### ISSUE TITLE
Build Failing in ESPHome / HA

### ISSUE THREAD

**Issue by numchucksoe** [KaufHA/kauf-rgbww-bulbs#65]
INFO ESPHome 2024.6.4
INFO Reading configuration /config/esphome/garage-left-replacement.yaml...
INFO Updating https://github.com/KaufHA/kauf-rgbww-bulbs@None
ERROR Unable to load component button:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 176, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/esphome/esphome/components/button/__init__.py", line 48, in <module>
    cv.ENTITY_BASE_SCHEMA.extend(web_server.WEBSERVER_SORTING_SCHEMA)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'esphome.components.web_server' has no attribute 'WEBSERVER_SORTING_SCHEMA'
Failed config

button: [source /data/packages/0cf47246/kauf-bulb.yaml:100]
  
  Component not found: button.
  - platform: restart
    id: restart_button
    name: Garage-Left-Replacement Restart Firmware
    entity_category: diagnostic
    disabled_by_default: true

--
substitutions:
  name: "garage-left-replacement"
  device_name: garage-left-replacement
  friendly_name: Garage-Left-Replacement
packages:
  kauf.rgbww: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: xxx

wifi:
  ssid: !secret hidden_wifi_ssid
  password: !secret hidden_wifi_password
  fast_connect: True

**Comment by bkaufx** [comment]
You are on an old version of the yaml.   Something with ESPHome keeps it from checking for updates in some cases.  You need to delete the .esphome/packages folder or reinstall the add-on.
